### ISSUE TITLE
Idea: how about renaming config into "textbook"

### ISSUE THREAD

**Issue by igrep** [sue445/rubicure#117]
# Problem

I've been feeling the directory name `config` sounds weird, as if it could be changed by users, or it shows as if PreCures were just a kind of machine or program (Yeah, rubicure is actually a program though :sweat_smile: ).

# (One) Solution

I've made up a very fancy name when creating the Haskell version of `config`:
`textbook`, after "Textbook of PreCures"（プリキュアの教科書）!

(If you don't mind and prefer, let's discuss in Japanese!) 
（日本語で議論して差し支えないならもちろん日本語で大丈夫です！）

**Comment by sue445** [comment]
（英語は得意でないので日本語で失礼します）

> I've been feeling the directory name config sounds weird,

これに関しては言われれば「はい確かにそうですね」という感じなのですが、`config` ディレクトリはgem利用者側に提供してるAPIではなくあくまでもrubicure自身の設定という位置づけなので個人的に違和感はありません。

「`config` だと変更可能に聞こえる（見える）」というのは主観なのでこれ以上は水掛け論にしかならないのでこれ以上議論するつもりはありません。

> (One) Solution

`textbook` は面白いのですが、（少なくともrubyのプロダクトだと）そういう名前を使ってるのは見たことがないので違和感があります。（違和感があるとそれだけ初めてソースを読む側にストレスがかかる）

採用するとしたら `data` ですかね。

**Comment by igrep** [comment]
> （違和感があるとそれだけ初めてソースを読む側にストレスがかかる）

😕 うーん、その考えは及びませんでした。。。

仮に誰かに引き継ぐにしても、中身を見ればすぐわかるレベルのものだと思うのですが。。。
最悪textbook/READMEでも加えればよいレベルではないかと思います。

> （少なくともrubyのプロダクトだと）そういう名前を使ってるのは見たことがないので違和感があります。

面白いからこそ独自性があって、違和感を与えるようになるのではないかと思います。
この違和感はちゃんと由来を教えれば（少なくともプリキュアに親しみのある人にとっては）むしろ強く印象づけられるし、楽しくソースを読めるのではないかと思います。

ただ、確かに、おっしゃるとおりいずれにしても主観の問題になってしまうのも事実なので、それでも否定的なのであればそのままクローズしていただいてかまいません。

**Comment by sue445** [comment]
> 最悪textbook/READMEでも加えればよいレベルではないかと思います。

code smell（コードの異臭）というレベルでの違和感なのでドキュメント書いて解決するものではないと思います。

それにドキュメント読まない人も一定数はいるのでその度に質問されて答えて体力を使いたくはありません。（後述）

> この違和感はちゃんと由来を教えれば

コードを書いた人が教えなければ理解できない、このことは僕はreadable codeという観点においては「悪」だと思っています。

また、聞かれる度に僕自身がいちいち答えたくありません。実際にgithubで公開してる僕のプロダクトに対してissueでトラブルシューティングの質問（英語）はよくきますが、英語で質問されるとそれを理解しやりとりするのにすごい時間と体力を使います。

妥当な質問であればいいのですが、issueでクレクレ君が湧きすぎて実際にissueの機能そのものを閉じたリポジトリもあります。（PullRequestは閉じていないので「文句があるならコード書け」という方針）

gemだけで30個以上メンテしているのにわざわざメンテが大変になることは極力したくありません。

`config` を `data` にするのは分かりやすいし納得感はありますが、`config` を `textbook` にすると上記のように将来的に僕自身のメンテナンスコストが高くなると思われるので、すみませんがクローズさせてもらいます。
