### ISSUE TITLE
Unknown warnings about an instance variable initialization in girl.rb

### ISSUE THREAD

**Issue by kaosf** [sue445/rubicure#130]
The following log was found in my gem project [rubicure_fuzzy_match](https://github.com/kaosf/rubicure_fuzzy_match) test (`bundle exec rake`).

```
...

/home/travis/.rvm/gems/ruby-2.3.3/gems/rubicure-0.4.12/lib/rubicure/girl.rb:159: warning: instance variable @colors not initialized
/home/travis/.rvm/gems/ruby-2.3.3/gems/rubicure-0.4.12/lib/rubicure/girl.rb:133: warning: instance variable @config not initialized

...
```

For the entire log:

- Ruby 2.3.3: https://travis-ci.org/kaosf/rubicure_fuzzy_match/jobs/186894989
- Ruby 2.4.0: https://travis-ci.org/kaosf/rubicure_fuzzy_match/jobs/186894990

Other versions information:

- Bundler 1.13.7
- Rake 12.0.0
- test_unit 3.2.3

Thanks.

**Comment by kaosf** [comment]
続きは日本語織り交ぜつつでもOKモフ

**Comment by sue445** [comment]
@kaosf I'm sorry for the late reply.

I think this is due to `ruby -w` option.

> /home/travis/.rvm/rubies/ruby-2.4.0/bin/ruby -w -I"lib:test" -I"/home/travis/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib" "/home/travis/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/test_rubicure_fuzzy_match.rb" 

```sh
$ ruby --help | grep "\-w"
  -w              turn warnings on for your script
```

**Comment by kaosf** [comment]
I got it. Thanks a lot!

There is no warning message (expect for Fixnum and Bignum messages) when running the following command in my environment.

```
bundle exec ruby -I"lib:test" -I"vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib" "vendor/bundle/ruby/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/test_helper.rb" "test/test_rubicure_fuzzy_match.rb"
```

**Comment by sue445** [comment]
> expect for Fixnum and Bignum messages

* :no_good: : expect
* 🙆 : except

😇

**Comment by kaosf** [comment]
yep, i missed the spell. :skull:  "except" is correct.

**Comment by sue445** [comment]
![_](https://cloud.githubusercontent.com/assets/608755/21982117/257e5b40-dc2e-11e6-8d80-0b9b33496094.jpg)

**Comment by kaosf** [comment]
can i close this issue now?
