### ISSUE TITLE
"(!Cure.cosmo).name" may return "バケニャーン" or "ブルーキャット"

### ISSUE THREAD

**Issue by seaki** [sue445/rubicure#209]
元々敵側にいたわけではなくて、レインボー星の仲間を救うためにノットレイダーに潜入していたわけだから、寝返ったわけじゃないから、Not operatorで表現するとノットレイにされちゃうな……。どう表現したらいいんだろう。

**Comment by sue445** [comment]
まだ妄想レベルですが  `Cure.cosmo.transform!(:rainbow_perfume)` で対応しようとは考えています
